### ISSUE TITLE
Error running qiime_to_lefse.py

### ISSUE THREAD

**Issue by mnhuda** [gblanchard4/qiime_to_lefse#1]
Hey,

I got the following error. Any suggestion?

Regards,
Nazmul

---

Traceback (most recent call last):
  File "qiime_to_lefse.py", line 96, in <module>
    main()
  File "qiime_to_lefse.py", line 89, in main
    append_otu_info(taxa_table, outfile, sample_dict, categories)
  File "qiime_to_lefse.py", line 23, in append_otu_info
    category1_line += "{}\t".format(sample_dict[sample_id][0])
KeyError: '6007w11\r'

---

**Comment by gblanchard4** [comment]
The `/r` in the `KeyError` leads me to believe you are on a Windows machine, is this correct? You may need to convert your new lines to linux compatible ones, the `/n` is what my script is looking for. 

Does this help any?

**Comment by mnhuda** [comment]
Thank you for your reply. Yes, I am on windows PC but I was running the code on Ubuntu in virtualbox. I am not a computer science person. Wondering if you please tell me which file I need to convert and how. Thanks for creating qiime_to_lefse.py

Regards,
Nazmul

**Comment by gblanchard4** [comment]
You may need to install dos2unix on the Ubuntu box, you should be able to using `sudo apt-get install dos2unix`. Then convert the file using `dos2unix your-file` 

Once it's converted you should be able to run the script in the form

```
python qiime_to_lefse.py -m mappingfile.txt -t otus_L3.txt -c category1,category2 -o converted_lefse.txt
```

If this gives you any issues just let me know and I'll continue working through your issues!

**Comment by mnhuda** [comment]
Great!! It worked! Thanks a lot.
